SoundSphere/SoundSphere/Models/ArtistViewModel.cs
namespace SoundSphere.Models
{
    public class ArtistViewModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }
}

SoundSphere/SoundSphere/Models/ErrorViewModel.cs
namespace SoundSphere.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

SoundSphere/SoundSphere/Models/GenreViewModel.cs
namespace SoundSphere.Models
{
	public class GenreViewModel
	{
		public int Id { get; set; }
		public string Name { get; set; }
	}
}

SoundSphere/SoundSphere/Models/SongViewModel.cs
namespace SoundSphere.Models
{
    public class SongViewModel
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public ArtistViewModel Artist { get; set; }
        public GenreViewModel Genre { get; set; }
    }
}

SoundSphere/SoundSphere/Controllers/ArtistController.cs
using DAL;
using Logic;
using Logic.Models;
using Microsoft.AspNetCore.Mvc;
using SoundSphere.Models;

namespace SoundSphere.Controllers
{
    public class ArtistController : Controller
    {
        ArtistService _artistService;
        public ArtistController(IArtistRepository artistRepository)
        {
            _artistService = new ArtistService(artistRepository);
        }
        public IActionResult Index()
        {
            List<ArtistModel> artistModels = _artistService.LoadAllArtists();
            List<ArtistViewModel> artistViewModels = new List<ArtistViewModel>();
            foreach(ArtistModel artistModel in artistModels)
            {
                ArtistViewModel artistViewModel = new ArtistViewModel();
                artistViewModel.Id = artistModel.Id;
                artistViewModel.Name = artistModel.Name;
                artistViewModels.Add(artistViewModel);
            }
            return View(artistViewModels);
        }
    }
}

SoundSphere/SoundSphere/Controllers/GenreController.cs
using Microsoft.AspNetCore.Mvc;

namespace SoundSphere.Controllers
{
	public class GenreController : Controller
	{
		public IActionResult Add()
		{
			return View();
		}
		[HttpPost]
		public IActionResult AddGenre(string? genre)
		{

			return View();
		}
	}
}

SoundSphere/SoundSphere/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using SoundSphere.Models;

namespace SoundSphere.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

SoundSphere/SoundSphere/Controllers/SongController.cs
using Microsoft.AspNetCore.Mvc;
using Logic;
using DAL;
using Logic.Models;
using SoundSphere.Models;

namespace SoundSphere.Controllers
{
    public class SongController : Controller
    {
        SongService _songService;
        public SongController(ISongRepository _songRepository, IArtistRepository _artistRepository, IGenreRepository _genreRepository)
        {
            _songService = new SongService(_songRepository, _artistRepository, _genreRepository);
        }
        public IActionResult Index()
        {
            List<SongModel> songModels = _songService.LoadAllSongs();
            List<SongViewModel> songViewModels = new List<SongViewModel>();
            foreach(SongModel songModel in songModels)
            {
                SongViewModel song = new SongViewModel();
                song.Id = songModel.Id;
                song.Title = songModel.Title;
                ArtistViewModel artist = new ArtistViewModel();
                artist.Id = songModel.Artist.Id;
                artist.Name = songModel.Artist.Name;
                song.Artist = artist;
                GenreViewModel genre = new GenreViewModel();
                genre.Id = songModel.Genre.Id;
                genre.Name = songModel.Genre.Name;
                song.Genre = genre;
                songViewModels.Add(song);
            }
            return View(songViewModels);
        }
        public IActionResult Add()
        {
            return View();
        }
        //public IActionResult AddSong(string title, string artist)
        //{
        //    //Song song = new Song();
        //    //song.SetDetails(0, title);
        //    //bool check = songService.AddSong(song);
        //    //return RedirectToAction("Index");
        //}
    }
}

SoundSphere/SoundSphere/Views/Artist/Index.cshtml
@model List<ArtistViewModel>
@if (Model.Any())
{
    <div class="row row-cols-3 row-gap-3">
    @foreach(ArtistViewModel artist in Model)
    {
        <div class="col mt-10">
            <div class="card">
                <div class="card-body">
                    <div class="card-title fs-4 fw-bold">@artist.Name</div>
                    <div class="card-text">
                        <button type="button" class="btn btn-outline-primary">Learn more</button>
                    </div>
                </div>
            </div>
        </div>
    }
    </div>
}
else
{
    <p class="text-center">No artists are found.</p>
}

SoundSphere/SoundSphere/Views/Genre/Add.cshtml
@model GenreViewModel
<p class="fs-1 text-center fw-bold">Add genre</p>
<form method="POST" asp-action="AddGenre" asp-controller="Genre" class="text-center">
    <p>
        <label for="title">Genre</label><br />
        <input type="text" id="genre" name="genre" placeholder="Genre" required asp-for="Name"/>
    </p>
    <input type="submit" value="Submit" />
</form>

SoundSphere/SoundSphere/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

SoundSphere/SoundSphere/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SoundSphere</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/custom.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SoundSphere.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SoundSphere</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Song" asp-action="Index">Songs</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Artist" asp-action="Index">Artists</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - SoundSphere - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

SoundSphere/SoundSphere/Views/Song/Add.cshtml
<p class="fs-1 text-center fw-bold">Add song</p>
<form method="POST" asp-action="AddSong" class="text-center">
    <p>
        <label for="title">Title</label><br />
        <input type="text" id="title" name="title" placeholder="Title" required />
    </p>
    <p>
        <label for="artist">Artist</label><br />
        <input type="text" id="artist" name="artist" placeholder="Artist" required />
    </p>
    <input type="submit" value="Submit" />
</form>

SoundSphere/SoundSphere/Views/Song/Index.cshtml
@model List<SongViewModel>
<p class="fs-1 text-center fw-bold">Songs</p>
<p class="text-center"><a type="button" class="btn btn-primary" asp-action="Add" asp-controller="Song">Add song</a></p>
@if(Model.Any())
{
    <div class="row row-cols-3 row-gap-3">
    @foreach(SongViewModel song in Model)
    {
        <div class="col mt-10">
            <div class="card">
                <div class="card-body">
                    <div class="card-title fs-4 fw-bold">@song.Title</div>
                    <div class="card-text">
                        <p><span class="fw-bold">Artist:</span> @song.Artist.Name</p>
                        <p><span class="fw-bold">Genre:</span> @song.Genre.Name</p>
                        <button type="button" class="btn btn-outline-primary">Learn more</button>
                    </div>

                </div>
            </div>
        </div>
    }
    </div>
}
else{
    <p class="text-center">There are no songs found.</p>
}